In [1]:
import numpy as np

In [2]:
m = np.matrix('1 2 3 4; 5 6 7 8; 9 1 5 7')
print(m)

[[1 2 3 4]
 [5 6 7 8]
 [9 1 5 7]]


In [3]:
type(m)

numpy.matrix

In [4]:
m = np.array(m)
type(m)

numpy.ndarray

In [5]:
m

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 1, 5, 7]])

In [6]:
m.shape

(3, 4)

In [7]:
m.max()

9

In [8]:
np.max(m)

9

In [9]:
m.max()

9

In [10]:
m.max(axis=1)

array([4, 8, 9])

In [11]:
m.max(axis=0)

array([9, 6, 7, 8])

In [12]:
# argmax	Индексы элементов с максимальным значением (по осям)
# argmin	Индексы элементов с минимальным значением (по осям)
# max	Максимальные значения элементов (по осям)
# min	Минимальные значения элементов (по осям)
# mean	Средние значения элементов (по осям)
# prod	Произведение всех элементов (по осям)
# std	Стандартное отклонение (по осям)
# sum	Сумма всех элементов (по осям)
# var	Дисперсия (по осям)

In [13]:
m.mean()

4.833333333333333

In [14]:
m.mean(axis=1)

array([2.5, 6.5, 5.5])

In [15]:
m.sum()

58

In [16]:
m.sum(axis=0)

array([15,  9, 15, 19])

In [17]:
m[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
m[2]

array([9, 1, 5, 7])

In [19]:
m[0:0]

array([], shape=(0, 4), dtype=int32)

In [20]:
m[0, 0]

1

In [21]:
m[-1:, -2:]

array([[5, 7]])

In [22]:
m[1, :]

array([5, 6, 7, 8])

In [23]:
m[:3]

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 1, 5, 7]])

In [24]:
m[:,3]

array([4, 8, 7])

In [25]:
m

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 1, 5, 7]])

In [26]:
len(m)

3

In [27]:
9 in m

True

In [28]:
0 in m

False

In [29]:
a = np.array(range(10), float)

In [30]:
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [31]:
a.reshape(5,2)

array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]])

In [32]:
a.shape

(10,)

In [33]:
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [34]:
a = a.reshape(5,2)

In [35]:
a

array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]])

In [36]:
a = np.array([1, 2, 3], float)
b = a
c =  a.copy()
a[0] = 0

In [37]:
a

array([0., 2., 3.])

In [38]:
b

array([0., 2., 3.])

In [39]:
c

array([1., 2., 3.])

In [40]:
a = np.array([1, 2, 3], float)
a.tolist()

[1.0, 2.0, 3.0]

In [41]:
a = np.array([1, 2, 3], float)
s = a.tostring()
s

b'\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x08@'

In [42]:
np.fromstring(s)

C:\Users\User\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  """Entry point for launching an IPython kernel.


array([1., 2., 3.])

In [43]:
a.fill(0)
a

array([0., 0., 0.])

In [44]:
a = np.array(range(6), float).reshape((2, 3))
a

array([[0., 1., 2.],
       [3., 4., 5.]])

In [45]:
a.transpose()

array([[0., 3.],
       [1., 4.],
       [2., 5.]])

In [46]:
# Многомерный массив можно переконвертировать в одномерный при помощи метода flatten:
a = np.array([[1, 2, 3], [4, 5, 6]], float)
print(a)

a.flatten()

[[1. 2. 3.]
 [4. 5. 6.]]


array([1., 2., 3., 4., 5., 6.])

In [47]:
# Два или больше массивов можно сконкатенировать при помощи метода concatenate:

a = np.array([1,2], float)
b = np.array([3,4,5,6], float)
c = np.array([7,8,9], float)
np.concatenate((a, b, c))

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [48]:
# Если массив не одномерный, можно задать ось, по которой будет происходить соединение. 
# По умолчанию (не задавая значения оси), соединение будет происходить по первому измерению:

a = np.array([[1, 2], [3, 4]], float)
b = np.array([[5, 6], [7, 8]], float)
np.concatenate((a,b))


array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.]])

In [49]:
np.concatenate((a,b), axis=0)

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.]])

In [50]:
np.concatenate((a,b), axis=1)

array([[1., 2., 5., 6.],
       [3., 4., 7., 8.]])

In [51]:
# В заключении, размерность массива может быть увеличена при использовании константы newaxis в квадратных скобках:

a = np.array([1, 2, 3], float)
a

array([1., 2., 3.])

In [52]:
a[:,np.newaxis]

array([[1.],
       [2.],
       [3.]])

In [53]:
a[np.newaxis,:]

array([[1., 2., 3.]])

# Другие пути создания массивов

In [54]:
# Функция arange аналогична функции range, но возвращает массив:

np.arange(5, dtype=float)

array([0., 1., 2., 3., 4.])

In [55]:
np.arange(1, 6, 2, dtype=int)

array([1, 3, 5])

In [56]:
# Функции zeros и ones создают новые массивы с установленной размерностью, заполненные этими значениями.

np.ones((2,3), dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [57]:
np.zeros(7, dtype=int)

array([0, 0, 0, 0, 0, 0, 0])

In [58]:
# Функции zeros_like и ones_like могут преобразовать уже созданный массив, заполнив его нулями и единицами соответственно:

a = np.array([[1, 2, 3], [4, 5, 6]], float)
np.zeros_like(a)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [59]:
np.ones_like(a)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [60]:
np.identity(4, dtype=float)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [61]:
np.eye(4, k=1, dtype=float)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

# Математические операции над массивами

In [62]:
a = np.array([1,2,3], float)
b = np.array([5,2,6], float)

In [63]:
a + b

array([6., 4., 9.])

In [64]:
a - b

array([-4.,  0., -3.])

In [65]:
a % b

array([1., 0., 3.])

In [66]:
# если размерность массивов не совпадает, они будут преобразованы для выполнения математических операций. 
# Это зачастую означает, что меньший массив будет использован несколько раз для завершения операций.

a = np.array([[1, 2], [3, 4], [5, 6]], float)
b = np.array([-1, 3], float)

a + b

array([[0., 5.],
       [2., 7.],
       [4., 9.]])

In [67]:
# однако, когда преобразование играет роль, мы можем использовать константу newaxis, чтобы изменить преобразование:

a = np.zeros((2,2), float)
b = np.array([-1., 3.], float)

a + b

array([[-1.,  3.],
       [-1.,  3.]])

In [68]:
a + b[np.newaxis,:]

array([[-1.,  3.],
       [-1.,  3.]])

In [69]:
a + b[:, np.newaxis]

array([[-1., -1.],
       [ 3.,  3.]])

In [70]:
# функции: abs, sign, sqrt, log, log10, exp, sin, cos, tan, arcsin, 
# arccos, arctan, sinh, cosh, tanh, arcsinh, arccosh, и arctanh.

a = np.array([1, 4, 9], float)
np.sqrt(a)

array([1., 2., 3.])

In [71]:
# Функции floor, ceil и rint возвращают нижние, верхние или ближайшие (округлённое) значение:

a = np.array([1.1, 1.5, 1.9], float)
np.floor(a)

array([1., 1., 1.])

In [72]:
np.ceil(a)

array([2., 2., 2.])

In [73]:
np.rint(a)

array([1., 2., 2.])

In [74]:
np.pi

3.141592653589793

In [75]:
np.e

2.718281828459045

# Перебор элементов массива

In [76]:
a = np.array([1, 4, 5], int)
for x in a:
    print(x)

1
4
5


In [77]:
a = np.array([[1, 2], [3, 4], [5, 6]], float)
for x in a:
    print(x)

[1. 2.]
[3. 4.]
[5. 6.]


In [78]:
for (x, y) in a:
    print(x*y)

2.0
12.0
30.0


# Базовые операции над массивами

In [79]:
a = np.array([2, 4, 3], float)
a.sum()

9.0

In [80]:
a.prod()

24.0

In [81]:
np.sum(a)

9.0

In [82]:
np.prod(a)

24.0

In [83]:
a.mean()

3.0

In [84]:
# вариация и девиация:
a.var()

0.6666666666666666

In [85]:
a.std()

0.816496580927726

In [86]:
# Функции argmin и argmax возвращают индекс минимального или максимального элемента:

a.argmin()

0

In [87]:
a.argmax()

1

In [89]:
a.sort()
a

array([2., 3., 4.])

In [91]:
# Значения в массиве могут быть «сокращены», чтобы принадлежать заданному диапазону. 
# Это тоже самое что применять min(max(x, minval), maxval) к каждому элементу x:
a = np.array([6, 2, 5, -1, 0], float)
a.clip(0, 5)

array([5., 2., 5., 0., 0.])

In [92]:
a = np.array([1, 1, 4, 5, 5, 5, 7], float)
np.unique(a)

array([1., 4., 5., 7.])

In [93]:
a = np.array([[1, 2], [3, 4]], float)
a.diagonal()

array([1., 4.])

# Операторы сравнения и тестирование значений

In [94]:
a = np.array([1, 3, 0], float)
b = np.array([0, 3, 2], float)

In [95]:
a > b

array([ True, False, False])

In [96]:
a == b

array([False,  True, False])

In [97]:
a <= b

array([False,  True,  True])

In [98]:
c = a > b
c

array([ True, False, False])

In [99]:
# Операторы any и all могут быть использованы для определения истинны ли хотя бы один или все элементы соответственно:
c = np.array([ True, False, False], bool)
any(c)

True

In [100]:
all(c)

False

# Комбинированные булевы выражения могут быть применены к массивам по принципу элемент — элемент используя специальные функции logical_and, logical_or и logical_not:

In [101]:
a = np.array([1, 3, 0], float)
np.logical_and(a > 0, a < 3)

array([ True, False, False])

In [104]:
b = np.array([True, False, False], bool)
np.logical_not(b)

array([False,  True,  True])

In [105]:
c = np.array([False, True, False], bool)
np.logical_or(b, c)

array([ True,  True, False])

In [106]:
# Функция where создает новый массив из двух других массивов одинаковых длин используя булев фильтр 
#для выбора межу двумя элементами. Базовый синтаксис: where(boolarray, truearray, falsearray):

a = np.array([1, 3, 0], float)
np.where(a != 0, 1 / a, a)

C:\Users\User\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: divide by zero encountered in true_divide
  """


array([1.        , 0.33333333, 0.        ])

In [107]:
np.where(a > 0, 3, 2)

array([3, 3, 2])

In [108]:
a = np.array([[0, 1], [3, 0]], float)
a.nonzero()

(array([0, 1], dtype=int64), array([1, 0], dtype=int64))

In [109]:
a = np.array([1, np.NaN, np.Inf], float)
a

array([ 1., nan, inf])

In [110]:
np.isnan(a)

array([False,  True, False])

In [111]:
np.isfinite(a)

array([ True, False, False])

# Выбор элементов массива и манипуляция с ними

In [112]:
a = np.array([[6, 4], [5, 9]], float)

In [113]:
a >= 6

array([[ True, False],
       [False,  True]])

In [114]:
a[a >= 6]

array([6., 9.])

In [115]:
a = np.array([[6, 4], [5, 9]], float)
sel = (a >= 6)
a[sel]

array([6., 9.])

In [117]:
a[np.logical_and(a > 3, a < 9)]

array([6., 4., 5.])

In [118]:
a = np.array([2, 4, 6, 8], float)
b = np.array([0, 0, 1, 3, 2, 1], int) # INDEXIS
a[b]

array([2., 2., 4., 8., 6., 4.])

In [119]:
a = np.array([2, 4, 6, 8], float)
a[[0, 0, 1, 3, 2, 1]]

array([2., 2., 4., 8., 6., 4.])

In [120]:
# Для многомерных массивов, нам необходимо передать несколько одномерных целочисленных массивов в оператор
# доступа индексу (Прим. переводчика: в нашем случае индексы это массивы) для каждой оси. 
# Потом каждый из массивов проходит такую последовательность: первый элемент соответствует индексу строки, 
# который является первым элементом массива b, второй элемент соответствует индексу столбца, 
# который является первым элементом массива c и так далее. (Прим. переводчика: первый массив [2, 2] и
# второй [1, 4], имеем на выходе элементы с индексами [2, 1] и [2, 4]) Пример:

a = np.array([[1, 4], [9, 16]], float)
b = np.array([0, 0, 1, 1, 0], int) 
c = np.array([0, 1, 1, 1, 1], int)
a[b,c] # 0 row 0 colum; 

array([ 1.,  4., 16., 16.,  4.])

In [121]:
# Специальная функция take доступна для выполнения выборки с целочисленными массивами. 
# Это работает также как и использования оператора взятия по индексу:

a = np.array([2, 4, 6, 8], float)
b = np.array([0, 0, 1, 3, 2, 1], int)
a.take(b)

array([2., 2., 4., 8., 6., 4.])

In [122]:
a = np.array([[0, 1], [2, 3]], float)
b = np.array([0, 0, 1], int)
a.take(b, axis=0)

array([[0., 1.],
       [0., 1.],
       [2., 3.]])

In [123]:
a.take(b, axis=1)

array([[0., 0., 1.],
       [2., 2., 3.]])

In [124]:
a = np.array([0, 1, 2, 3, 4, 5], float)
b = np.array([9, 8, 7], float)
a.put([0, 3], b)
a

array([9., 1., 2., 8., 4., 5.])

In [125]:
a.put([0, 3, 5], b)
a

array([9., 1., 2., 8., 4., 7.])

# Векторная и матричная математика

In [127]:
# NumPy обеспечивает много функций для работы с векторами и матрицами. 
# Функция dot возвращает скалярное произведение векторов:

a = np.array([1, 2, 3], float)
b = np.array([0, 2, 1], float)
np.dot(a, b)

7.0

In [128]:
# Функция dot также может умножать матрицы:

a = np.array([[0, 1], [2, 3]], float)
b = np.array([2, 3], float)
c = np.array([[1, 1], [4, 0]], float)
a

array([[0., 1.],
       [2., 3.]])

In [129]:
np.dot(b, a)  

array([ 6., 11.])

In [130]:
np.dot(a, b)

array([ 3., 13.])

In [131]:
np.dot(a, c)

array([[ 4.,  0.],
       [14.,  2.]])

In [132]:
np.empty(5) # одномерный массив из пяти элементов, память для которого выделена, но не инициализирована
np.zeros((10, 7)) # массив размером 10x7, заполненный нулями 
np.ones((3,3,3)) # массив размером 3х3х3, заполненный единицами 
np.eye(3) # единичная матрица (элементы главной диагонали равны 1, остальные — 0) размера 3х3
np.full((3, 5), 3.14)  # массив 3x5 заполненный числом 3.14
np.arange(0, 21, 7)  # одномерный массив, заполненный числами в диапазоне от 0 до 20 с шагом 7
np.linspace(0, 1, 5)  # массив из пяти чисел, равномерно распределённых в интервале между 0 и 1 включительно
np.random.randint(0, 10, (3, 3))  # массив размера 3х3, заполненный случайными числами из диапазона от 0 до 9 (включительно)

array([[9, 5, 4],
       [5, 0, 6],
       [6, 0, 9]])

In [136]:
np.empty(4)

array([0.25, 0.5 , 0.75, 1.  ])

In [137]:
my_secret = [x for x in range(1, 301, 7) if x%10 == 7 or x%10 == 1]
np.array([my_secret, [x/2 for x in my_secret], [x-100 for x in my_secret]])

array([[  1. ,  57. ,  71. , 127. , 141. , 197. , 211. , 267. , 281. ],
       [  0.5,  28.5,  35.5,  63.5,  70.5,  98.5, 105.5, 133.5, 140.5],
       [-99. , -43. , -29. ,  27. ,  41. ,  97. , 111. , 167. , 181. ]])

In [138]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [140]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [141]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [142]:
np.full((5,5), 1)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [143]:
np.random.randint(0, 5, 3)

array([0, 1, 4])

In [144]:
np.random.randint(0, 5, (3, 3))

array([[2, 4, 1],
       [0, 1, 2],
       [2, 0, 2]])

In [145]:
np.array([i for i in range(11) if i%2])

array([1, 3, 5, 7, 9])

In [150]:
my_array = np.array([x for x in range(10)])


my_array[1:8:3]

array([1, 4, 7])

In [147]:
my_array[5]

5

In [148]:
my_array[-1]

9

In [149]:
my_array[3:6]

array([3, 4, 5])

# 9.2

In [152]:
my_array = np.array([[1,2,3,4], [10,11,12,13], [45,46,47,48]])
my_array[1,2]

12

In [153]:
my_array[1][2]

12

In [154]:
my_array[1]

array([10, 11, 12, 13])

In [155]:
my_array[:,2]

array([ 3, 12, 47])

In [236]:
first_line = [x*y for x in range(2, 100, 6) for y in range (7, 1, -2)]
second_line = [x ** 0.5 for x in range(1000, 1101, 2)]
third_line = [x**2 for x in range(51)]

In [237]:
big_secret = np.array([first_line, second_line, third_line, second_line, first_line])

In [238]:
big_secret[1]

array([31.62, 31.65, 31.69, 31.72, 31.75, 31.78, 31.81, 31.84, 31.87,
       31.91, 31.94, 31.97, 32.  , 32.03, 32.06, 32.09, 32.12, 32.16,
       32.19, 32.22, 32.25, 32.28, 32.31, 32.34, 32.37, 32.4 , 32.43,
       32.47, 32.5 , 32.53, 32.56, 32.59, 32.62, 32.65, 32.68, 32.71,
       32.74, 32.77, 32.8 , 32.83, 32.86, 32.89, 32.92, 32.95, 32.98,
       33.02, 33.05, 33.08, 33.11, 33.14, 33.17])

In [239]:
big_secret[2]

array([   0.,    1.,    4.,    9.,   16.,   25.,   36.,   49.,   64.,
         81.,  100.,  121.,  144.,  169.,  196.,  225.,  256.,  289.,
        324.,  361.,  400.,  441.,  484.,  529.,  576.,  625.,  676.,
        729.,  784.,  841.,  900.,  961., 1024., 1089., 1156., 1225.,
       1296., 1369., 1444., 1521., 1600., 1681., 1764., 1849., 1936.,
       2025., 2116., 2209., 2304., 2401., 2500.])

In [240]:
big_secret[0]

array([ 14.,  10.,   6.,  56.,  40.,  24.,  98.,  70.,  42., 140., 100.,
        60., 182., 130.,  78., 224., 160.,  96., 266., 190., 114., 308.,
       220., 132., 350., 250., 150., 392., 280., 168., 434., 310., 186.,
       476., 340., 204., 518., 370., 222., 560., 400., 240., 602., 430.,
       258., 644., 460., 276., 686., 490., 294.])

In [241]:
big_secret[3]

array([31.62, 31.65, 31.69, 31.72, 31.75, 31.78, 31.81, 31.84, 31.87,
       31.91, 31.94, 31.97, 32.  , 32.03, 32.06, 32.09, 32.12, 32.16,
       32.19, 32.22, 32.25, 32.28, 32.31, 32.34, 32.37, 32.4 , 32.43,
       32.47, 32.5 , 32.53, 32.56, 32.59, 32.62, 32.65, 32.68, 32.71,
       32.74, 32.77, 32.8 , 32.83, 32.86, 32.89, 32.92, 32.95, 32.98,
       33.02, 33.05, 33.08, 33.11, 33.14, 33.17])

In [242]:
big_secret[4]

array([ 14.,  10.,   6.,  56.,  40.,  24.,  98.,  70.,  42., 140., 100.,
        60., 182., 130.,  78., 224., 160.,  96., 266., 190., 114., 308.,
       220., 132., 350., 250., 150., 392., 280., 168., 434., 310., 186.,
       476., 340., 204., 518., 370., 222., 560., 400., 240., 602., 430.,
       258., 644., 460., 276., 686., 490., 294.])

In [243]:
big_secret.shape

(5, 51)

In [244]:
np.sum(third_line)

42925

In [245]:
big_secret[:51].sum()

71729.85284071535

In [246]:
big_secret[:,50].sum()

3154.332495807108

In [247]:
# Выделите из каждой строки массива big_secret первые 5 элементов. 
# Чему равна сумма элементов главной диагонали получившейся матрицы? 
# Округлите ответ до двух цифр после запятой:

new_array = big_secret[:,0:5]

In [248]:
new_array

array([[14.  , 10.  ,  6.  , 56.  , 40.  ],
       [31.62, 31.65, 31.69, 31.72, 31.75],
       [ 0.  ,  1.  ,  4.  ,  9.  , 16.  ],
       [31.62, 31.65, 31.69, 31.72, 31.75],
       [14.  , 10.  ,  6.  , 56.  , 40.  ]])

In [249]:
sum(new_array.diagonal())

121.37188663699624

In [250]:
# Выделите из каждой строки массива big_secret последние 5 элементов. 
# Чему равно произведение элементов главной диагонали получившейся матрицы?

new_array_2 = big_secret[:,-5:]

In [251]:
new_array_2

array([[ 460.  ,  276.  ,  686.  ,  490.  ,  294.  ],
       [  33.05,   33.08,   33.11,   33.14,   33.17],
       [2116.  , 2209.  , 2304.  , 2401.  , 2500.  ],
       [  33.05,   33.08,   33.11,   33.14,   33.17],
       [ 460.  ,  276.  ,  686.  ,  490.  ,  294.  ]])

In [252]:
new_array_2 = new_array_2.diagonal()
new_array_2

array([ 460.  ,   33.08, 2304.  ,   33.14,  294.  ])

In [253]:
# lambda new_array_2[i] * new_array_2[i+1]: for i in new_array_2

In [204]:
n = 1
for i in new_array_2:
    n *= i

In [205]:
n

341505315559.2347

# Особенность индексирования

In [207]:
my_array = np.random.randint(1, 100, (4, 6))
my_array

array([[47, 11, 67, 55, 59,  1],
       [43, 70, 92, 73, 44, 72],
       [20, 10, 32, 51, 93, 26],
       [36, 55, 82, 89, 78, 27]])

In [208]:
my_slice = my_array[1:3, 2:4]

In [209]:
my_slice

array([[92, 73],
       [32, 51]])

In [210]:
my_slice[:] = 0

In [211]:
my_array

array([[47, 11, 67, 55, 59,  1],
       [43, 70,  0,  0, 44, 72],
       [20, 10,  0,  0, 93, 26],
       [36, 55, 82, 89, 78, 27]])

In [229]:
np.set_printoptions(precision=2, suppress=True)

In [254]:
big_secret

array([[  14.  ,   10.  ,    6.  ,   56.  ,   40.  ,   24.  ,   98.  ,
          70.  ,   42.  ,  140.  ,  100.  ,   60.  ,  182.  ,  130.  ,
          78.  ,  224.  ,  160.  ,   96.  ,  266.  ,  190.  ,  114.  ,
         308.  ,  220.  ,  132.  ,  350.  ,  250.  ,  150.  ,  392.  ,
         280.  ,  168.  ,  434.  ,  310.  ,  186.  ,  476.  ,  340.  ,
         204.  ,  518.  ,  370.  ,  222.  ,  560.  ,  400.  ,  240.  ,
         602.  ,  430.  ,  258.  ,  644.  ,  460.  ,  276.  ,  686.  ,
         490.  ,  294.  ],
       [  31.62,   31.65,   31.69,   31.72,   31.75,   31.78,   31.81,
          31.84,   31.87,   31.91,   31.94,   31.97,   32.  ,   32.03,
          32.06,   32.09,   32.12,   32.16,   32.19,   32.22,   32.25,
          32.28,   32.31,   32.34,   32.37,   32.4 ,   32.43,   32.47,
          32.5 ,   32.53,   32.56,   32.59,   32.62,   32.65,   32.68,
          32.71,   32.74,   32.77,   32.8 ,   32.83,   32.86,   32.89,
          32.92,   32.95,   32.98,   33.02,   33.0

In [255]:
big_secret[::2, ::2] = -1
big_secret[1::2, 1::2] = 1

In [256]:
big_secret

array([[  -1.  ,   10.  ,   -1.  ,   56.  ,   -1.  ,   24.  ,   -1.  ,
          70.  ,   -1.  ,  140.  ,   -1.  ,   60.  ,   -1.  ,  130.  ,
          -1.  ,  224.  ,   -1.  ,   96.  ,   -1.  ,  190.  ,   -1.  ,
         308.  ,   -1.  ,  132.  ,   -1.  ,  250.  ,   -1.  ,  392.  ,
          -1.  ,  168.  ,   -1.  ,  310.  ,   -1.  ,  476.  ,   -1.  ,
         204.  ,   -1.  ,  370.  ,   -1.  ,  560.  ,   -1.  ,  240.  ,
          -1.  ,  430.  ,   -1.  ,  644.  ,   -1.  ,  276.  ,   -1.  ,
         490.  ,   -1.  ],
       [  31.62,    1.  ,   31.69,    1.  ,   31.75,    1.  ,   31.81,
           1.  ,   31.87,    1.  ,   31.94,    1.  ,   32.  ,    1.  ,
          32.06,    1.  ,   32.12,    1.  ,   32.19,    1.  ,   32.25,
           1.  ,   32.31,    1.  ,   32.37,    1.  ,   32.43,    1.  ,
          32.5 ,    1.  ,   32.56,    1.  ,   32.62,    1.  ,   32.68,
           1.  ,   32.74,    1.  ,   32.8 ,    1.  ,   32.86,    1.  ,
          32.92,    1.  ,   32.98,    1.  ,   33.0

In [257]:
sum(np.diagonal(big_secret))

-1.0

In [227]:
cond

array([ 14.,   6.,  40.,  98.,  42., 100., 182.,  78., 160., 266., 114.,
       220., 350., 150., 280., 434., 186., 340., 518., 222., 400., 602.,
       258., 460., 686., 294.])

In [298]:
z = np.arange(100)
z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [299]:
z = z.reshape(5,20)
z

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [300]:
z[::2, ::3]=-1

In [301]:
z

array([[-1,  1,  2, -1,  4,  5, -1,  7,  8, -1, 10, 11, -1, 13, 14, -1,
        16, 17, -1, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [-1, 41, 42, -1, 44, 45, -1, 47, 48, -1, 50, 51, -1, 53, 54, -1,
        56, 57, -1, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79],
       [-1, 81, 82, -1, 84, 85, -1, 87, 88, -1, 90, 91, -1, 93, 94, -1,
        96, 97, -1, 99]])

In [308]:
big_secret[::,:-6:-1]

array([[  -1.  ,  490.  ,   -1.  ,  276.  ,   -1.  ],
       [  33.17,    1.  ,   33.11,    1.  ,   33.05],
       [  -1.  , 2401.  ,   -1.  , 2209.  ,   -1.  ],
       [  33.17,    1.  ,   33.11,    1.  ,   33.05],
       [  -1.  ,  490.  ,   -1.  ,  276.  ,   -1.  ]])

In [309]:
np.prod(big_secret.diagonal())

-1.0

In [310]:
# Замена местами строк и столбцов двумерного массива называется транспонированием.
# Для выполнения этой операции в NumPy используется метод T:

my_array = np.array([[1,2,3,4,5], [6,7,8,9,10]])
my_array.T

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [311]:
# Для преобразования многомерного массива в одномерный используется метод flatten:

my_array = np.array([[1,2,3], [11,22,33], [111,222,333]])
my_array.flatten()

array([  1,   2,   3,  11,  22,  33, 111, 222, 333])

In [315]:
my_array = np.random.randint(0, 10, (3,4))
my_array

array([[8, 0, 3, 6],
       [0, 0, 7, 5],
       [1, 3, 7, 9]])

In [316]:
my_array<5

array([[False,  True,  True, False],
       [ True,  True, False, False],
       [ True,  True, False, False]])

In [317]:
my_array[my_array<5]

array([0, 3, 0, 0, 1, 3])

In [318]:
mask = np.array([1, 0, 1, 0], dtype=bool)
my_array[:, mask]

array([[8, 3],
       [0, 7],
       [1, 7]])

# Сортировка двумерных массивов

In [320]:
my_array = np.random.randint(0, 10, (4, 6))

np.sort(my_array, axis=1)


array([[3, 5, 8, 9, 9, 9],
       [0, 2, 4, 7, 8, 8],
       [0, 1, 2, 4, 5, 7],
       [1, 3, 3, 7, 8, 9]])

In [321]:
np.sort(my_array, axis=0)

array([[0, 1, 1, 7, 2, 5],
       [0, 2, 3, 8, 3, 5],
       [3, 4, 4, 9, 7, 8],
       [9, 9, 7, 9, 8, 8]])

In [322]:
first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100, 200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]

great_secret = np.array([first, second, third]).T

In [323]:
great_secret

array([[ 0.  ,  4.64, 66.67],
       [ 1.  ,  4.66, 40.  ],
       [ 1.41,  4.67, 67.33],
       [ 1.73,  4.69, 40.4 ],
       [ 2.  ,  4.7 , 68.  ],
       [ 2.24,  4.72, 40.8 ],
       [ 2.45,  4.73, 68.67],
       [ 2.65,  4.75, 41.2 ],
       [ 2.83,  4.76, 69.33],
       [ 3.  ,  4.78, 41.6 ],
       [ 3.16,  4.79, 70.  ],
       [ 3.32,  4.81, 42.  ],
       [ 3.46,  4.82, 70.67],
       [ 3.61,  4.83, 42.4 ],
       [ 3.74,  4.85, 71.33],
       [ 3.87,  4.86, 42.8 ],
       [ 4.  ,  4.88, 72.  ],
       [ 4.12,  4.89, 43.2 ],
       [ 4.24,  4.9 , 72.67],
       [ 4.36,  4.92, 43.6 ],
       [ 4.47,  4.93, 73.33],
       [ 4.58,  4.95, 44.  ],
       [ 4.69,  4.96, 74.  ],
       [ 4.8 ,  4.97, 44.4 ],
       [ 4.9 ,  4.99, 74.67],
       [ 5.  ,  5.  , 44.8 ],
       [ 5.1 ,  5.01, 75.33],
       [ 5.2 ,  5.03, 45.2 ],
       [ 5.29,  5.04, 76.  ],
       [ 5.39,  5.05, 45.6 ],
       [ 5.48,  5.07, 76.67],
       [ 5.57,  5.08, 46.  ],
       [ 5.66,  5.09, 77.33],
       [ 5

In [331]:
np.sum((np.cos(great_secret[0])))

0.16006721889793019

In [332]:
np.sum(great_secret[great_secret>50])

5470.0

In [344]:
print(great_secret.flatten()[148:151])

[ 5.3  49.6   7.07]


In [348]:
np.take(great_secret.flatten(), [150], axis = 0)

array([7.07])

In [350]:
print(great_secret.sort(axis=0))

None


In [352]:
great_secret[-1].sum()

115.12148016521353

In [356]:
students = np.array([[1, 135, 34, 4],
[2, 160, 43, 5],
[3, 163, 40, 4.3],
[4, 147, 44, 5],
[5, 138, 41, 4.7],
[6, 149, 54, 3.9],
[7, 136, 39, 4.2],
[8, 154, 48, 4.9],
[9, 137, 35, 3.7],
[10, 165, 60, 4.6]])

In [357]:
students

array([[  1. , 135. ,  34. ,   4. ],
       [  2. , 160. ,  43. ,   5. ],
       [  3. , 163. ,  40. ,   4.3],
       [  4. , 147. ,  44. ,   5. ],
       [  5. , 138. ,  41. ,   4.7],
       [  6. , 149. ,  54. ,   3.9],
       [  7. , 136. ,  39. ,   4.2],
       [  8. , 154. ,  48. ,   4.9],
       [  9. , 137. ,  35. ,   3.7],
       [ 10. , 165. ,  60. ,   4.6]])

In [358]:
mean = np.mean(students[:,-1])
mean

4.430000000000001

In [359]:
median = np.median(students[:,-1])
median

4.449999999999999

In [360]:
median = np.median(students[:,2])
median

42.0

In [361]:
mean = np.mean(students[:,2])
mean

43.8

In [362]:
std = np.std(students[:,-1])
std

0.4517742799230607

In [363]:
np.var(students[:, 2])

60.36

In [437]:
my_array = np.array([[1,2,3,4,5],
                     [6,7,8,9,10],
                     [11,12,13,14,15],
                     [16,17,18,19,20],
                     [21,22,23,24,25]])

my_array[1:4, 1:4]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [439]:
print(np.sin(my_array[1:4, 1:4]))
my_sin_ = np.sum(np.sin(my_array))
my_sin_

[[ 0.66  0.99  0.41]
 [-0.54  0.42  0.99]
 [-0.96 -0.75  0.15]]


-0.05812430261413351

In [453]:
my_array[1:4,1:4]=1
print(my_array)
ggg = (np.sin(my_array))
ggg[1:4,1:4]=1
np.sum(ggg)

[[ 1  2  3  4  5]
 [ 6  1  1  1 10]
 [11  1  1  1 15]
 [16  1  1  1 20]
 [21 22 23 24 25]]


7.571718421269144

In [441]:
ttt = np.sin(my_array[1:4, 1:4])
print(ttt)
ttt[1,1] = 1
print(ttt)
np.sum(ttt)

[[ 0.66  0.99  0.41]
 [-0.54  0.42  0.99]
 [-0.96 -0.75  0.15]]
[[ 0.66  0.99  0.41]
 [-0.54  1.    0.99]
 [-0.96 -0.75  0.15]]


1.9499902392900823

In [381]:
my_array[1:4, 1:4] = 1
print(my_array)
(np.sum(my_array))

[[ 1  2  3  4  5]
 [ 6  1  1  1 10]
 [11  1  1  1 15]
 [16  1  1  1 20]
 [21 22 23 24 25]]


217

In [373]:
np.sum(my_array)

217

In [382]:
my_array

array([[ 1,  2,  3,  4,  5],
       [ 6,  1,  1,  1, 10],
       [11,  1,  1,  1, 15],
       [16,  1,  1,  1, 20],
       [21, 22, 23, 24, 25]])

In [383]:
my_sin = np.array(np.sin(my_array))

In [399]:
test_1 = [x**2 for x in range(101, 1000, 2)]
test_1

[10201,
 10609,
 11025,
 11449,
 11881,
 12321,
 12769,
 13225,
 13689,
 14161,
 14641,
 15129,
 15625,
 16129,
 16641,
 17161,
 17689,
 18225,
 18769,
 19321,
 19881,
 20449,
 21025,
 21609,
 22201,
 22801,
 23409,
 24025,
 24649,
 25281,
 25921,
 26569,
 27225,
 27889,
 28561,
 29241,
 29929,
 30625,
 31329,
 32041,
 32761,
 33489,
 34225,
 34969,
 35721,
 36481,
 37249,
 38025,
 38809,
 39601,
 40401,
 41209,
 42025,
 42849,
 43681,
 44521,
 45369,
 46225,
 47089,
 47961,
 48841,
 49729,
 50625,
 51529,
 52441,
 53361,
 54289,
 55225,
 56169,
 57121,
 58081,
 59049,
 60025,
 61009,
 62001,
 63001,
 64009,
 65025,
 66049,
 67081,
 68121,
 69169,
 70225,
 71289,
 72361,
 73441,
 74529,
 75625,
 76729,
 77841,
 78961,
 80089,
 81225,
 82369,
 83521,
 84681,
 85849,
 87025,
 88209,
 89401,
 90601,
 91809,
 93025,
 94249,
 95481,
 96721,
 97969,
 99225,
 100489,
 101761,
 103041,
 104329,
 105625,
 106929,
 108241,
 109561,
 110889,
 112225,
 113569,
 114921,
 116281,
 117649,
 119025,
 

In [400]:
bigdata = np.array([test_1])

In [401]:
bigdata

array([[ 10201,  10609,  11025,  11449,  11881,  12321,  12769,  13225,
         13689,  14161,  14641,  15129,  15625,  16129,  16641,  17161,
         17689,  18225,  18769,  19321,  19881,  20449,  21025,  21609,
         22201,  22801,  23409,  24025,  24649,  25281,  25921,  26569,
         27225,  27889,  28561,  29241,  29929,  30625,  31329,  32041,
         32761,  33489,  34225,  34969,  35721,  36481,  37249,  38025,
         38809,  39601,  40401,  41209,  42025,  42849,  43681,  44521,
         45369,  46225,  47089,  47961,  48841,  49729,  50625,  51529,
         52441,  53361,  54289,  55225,  56169,  57121,  58081,  59049,
         60025,  61009,  62001,  63001,  64009,  65025,  66049,  67081,
         68121,  69169,  70225,  71289,  72361,  73441,  74529,  75625,
         76729,  77841,  78961,  80089,  81225,  82369,  83521,  84681,
         85849,  87025,  88209,  89401,  90601,  91809,  93025,  94249,
         95481,  96721,  97969,  99225, 100489, 101761, 103041, 

In [402]:
np.median(bigdata)

302501.0

In [403]:
np.std(bigdata)

292095.0301991155

In [408]:
np.corrcoef(bigdata[::2, ::2], bigdata[1::2, 1::2])

1.0

In [406]:
bigdata[::2, ::2]

array([[ 10201,  11025,  11881,  12769,  13689,  14641,  15625,  16641,
         17689,  18769,  19881,  21025,  22201,  23409,  24649,  25921,
         27225,  28561,  29929,  31329,  32761,  34225,  35721,  37249,
         38809,  40401,  42025,  43681,  45369,  47089,  48841,  50625,
         52441,  54289,  56169,  58081,  60025,  62001,  64009,  66049,
         68121,  70225,  72361,  74529,  76729,  78961,  81225,  83521,
         85849,  88209,  90601,  93025,  95481,  97969, 100489, 103041,
        105625, 108241, 110889, 113569, 116281, 119025, 121801, 124609,
        127449, 130321, 133225, 136161, 139129, 142129, 145161, 148225,
        151321, 154449, 157609, 160801, 164025, 167281, 170569, 173889,
        177241, 180625, 184041, 187489, 190969, 194481, 198025, 201601,
        205209, 208849, 212521, 216225, 219961, 223729, 227529, 231361,
        235225, 239121, 243049, 247009, 251001, 255025, 259081, 263169,
        267289, 271441, 275625, 279841, 284089, 288369, 292681, 

In [409]:
my_array = np.array([[1,2,3,4,5],
                     [6,7,8,9,10],
                     [11,12,13,14,15],
                     [16,17,18,19,20],
                     [21,22,23,24,25]])

In [415]:
my_array[1:4,1:4]=1

In [416]:
my_sin = np.sin(my_array)

In [417]:
my_sin

array([[ 0.84,  0.91,  0.14, -0.76, -0.96],
       [-0.28,  0.84,  0.84,  0.84, -0.54],
       [-1.  ,  0.84,  0.84,  0.84,  0.65],
       [-0.29,  0.84,  0.84,  0.84,  0.91],
       [ 0.84, -0.01, -0.85, -0.91, -0.13]])

In [420]:
my_sin[1:4,1:4] = 1
my_sin

array([[ 0.84,  0.91,  0.14, -0.76, -0.96],
       [-0.28,  1.  ,  1.  ,  1.  , -0.54],
       [-1.  ,  1.  ,  1.  ,  1.  ,  0.65],
       [-0.29,  1.  ,  1.  ,  1.  ,  0.91],
       [ 0.84, -0.01, -0.85, -0.91, -0.13]])

In [419]:
np.sum(my_sin)

7.571718421269144

In [454]:
my_array = np.array([[1,2,3,4,5],
                     [6,7,8,9,10],
                     [11,12,13,14,15],
                     [16,17,18,19,20],
                     [21,22,23,24,25]])
my_sin = np.sin(my_array)

In [455]:
my_sin

array([[ 0.84,  0.91,  0.14, -0.76, -0.96],
       [-0.28,  0.66,  0.99,  0.41, -0.54],
       [-1.  , -0.54,  0.42,  0.99,  0.65],
       [-0.29, -0.96, -0.75,  0.15,  0.91],
       [ 0.84, -0.01, -0.85, -0.91, -0.13]])

In [457]:
my_sin[1:4,1:4]=1
my_sin

array([[ 0.84,  0.91,  0.14, -0.76, -0.96],
       [-0.28,  1.  ,  1.  ,  1.  , -0.54],
       [-1.  ,  1.  ,  1.  ,  1.  ,  0.65],
       [-0.29,  1.  ,  1.  ,  1.  ,  0.91],
       [ 0.84, -0.01, -0.85, -0.91, -0.13]])

In [459]:
np.sum(my_sin)

7.571718421269144

In [507]:
my_array = np.array([[1,2,3,4,5],
                     [6,7,8,9,10],
                     [11,12,13,14,15],
                     [16,17,18,19,20],
                     [21,22,23,24,25]])
#my_array[1:4,1:4]=1

In [508]:
my_array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [488]:
np.sin(my_array)

array([[ 0.84,  0.91,  0.14, -0.76, -0.96],
       [-0.28,  0.84,  0.84,  0.84, -0.54],
       [-1.  ,  0.84,  0.84,  0.84,  0.65],
       [-0.29,  0.84,  0.84,  0.84,  0.91],
       [ 0.84, -0.01, -0.85, -0.91, -0.13]])

In [509]:
my_sin = my_array[0:5,0:4]

In [510]:
print(my_sin)

[[ 1  2  3  4]
 [ 6  7  8  9]
 [11 12 13 14]
 [16 17 18 19]
 [21 22 23 24]]


In [511]:
my_sin.reshape(10,2)

array([[ 1,  2],
       [ 3,  4],
       [ 6,  7],
       [ 8,  9],
       [11, 12],
       [13, 14],
       [16, 17],
       [18, 19],
       [21, 22],
       [23, 24]])

In [512]:
np.sum(np.sin(my_sin[:0]))

0.0

In [513]:
my_sin = my_sin.reshape(10,2)

In [514]:
my_sin = my_sin[:,0:]

In [515]:
np.sum(np.sin(my_sin))

0.013939742151403367