In [1]:
import numpy as np

In [5]:
a = np.array([[1,2],[-3,1],[1,2],[1,-1]])

In [6]:
a

array([[ 1,  2],
       [-3,  1],
       [ 1,  2],
       [ 1, -1]])

In [15]:
A = np.dot(a.T,a)

In [16]:
A

array([[12,  0],
       [ 0, 10]])

In [19]:
b = np.array([[1],[4],[5],[0]])
b

array([[1],
       [4],
       [5],
       [0]])

In [20]:
np.linalg.inv(A) * np.dot(a.T, b)

array([[-0.5, -0. ],
       [ 0. ,  1.6]])